version: "3.8"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - mongo

  frontend:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/.env:/usr/share/nginx/html/.env
    depends_on:
      - backend
